### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by mgeier** [spatialaudio/communication-acoustics-exercises#5]
http://tinyurl.com/qu-kemar

This is redirecting to https://dev.qu.tu-berlin.de/projects/measurements/wiki/2010-11-kemar-anechoic (see https://preview.tinyurl.com/qu-kemar).

https://github.com/spatialaudio/communication-acoustics-exercises/blob/1d9873e0a35fb7064aa63c67af69b142ad1751b5/brir.ipynb#L329

https://dev.qu.tu-berlin.de/projects/measurements/repository/raw/2010-11-kemar-anechoic/mat/QU_KEMAR_anechoic_2m.mat

https://github.com/spatialaudio/communication-acoustics-exercises/blob/1d9873e0a35fb7064aa63c67af69b142ad1751b5/brir.ipynb#L331

https://github.com/spatialaudio/communication-acoustics-exercises/blob/1d9873e0a35fb7064aa63c67af69b142ad1751b5/brir-solutions.ipynb#L666

The first URL is still not available, but the data file is now available at https://doi.org/10.5281/zenodo.4459911, more concretely at https://zenodo.org/record/4459911/files/QU_KEMAR_anechoic_2m.mat.

**Comment by fs446** [comment]
handled by PR #7
